# Generated by Django 3.2.17 on 2023-02-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0021_auto_20221218_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Aktivität', 'verbose_name_plural': 'Aktivitäten'},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Auszeichnung', 'verbose_name_plural': 'Auszeichnungen'},
        ),
        migrations.AlterModelOptions(
            name='badgedata',
            options={'ordering': ('display_order', 'slug'), 'verbose_name': 'Auszeichnungsdaten', 'verbose_name_plural': 'Auszeichnungsdaten'},
        ),
        migrations.AlterModelOptions(
            name='postflagreason',
            options={'verbose_name': 'Postmarkierungsgrund', 'verbose_name_plural': 'Postmarkierungsgründe'},
        ),
        migrations.AlterModelOptions(
            name='postrevision',
            options={'ordering': ('-revision',), 'verbose_name': 'Fragen Revision', 'verbose_name_plural': 'Fragen Revisionen'},
        ),
        migrations.AlterModelOptions(
            name='replyaddress',
            options={'verbose_name': 'Antwortadresse', 'verbose_name_plural': 'Antwortadressen'},
        ),
        migrations.AlterModelOptions(
            name='repute',
            options={'verbose_name': 'Ansehen', 'verbose_name_plural': 'Ansehen'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'Stimmen'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(default='de', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_language',
            field=models.CharField(choices=[('de', 'Deutsch')], default='de', max_length=16),
        ),
    ]
